# Generated by Django 5.1.3 on 2024-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=300)),
                ('todo_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
