# Generated by Django 5.1.3 on 2025-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_completed',
            new_name='completed',
        ),
    ]
